// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devexps/go-bootstrap/gen/api/go/conf/v1"
	"github.com/devexps/go-micro/v2"
	"github.com/devexps/go-micro/v2/log"
	"github.com/devexps/go-micro/v2/registry"
	"github.com/devexps/go-microservices-demo/app/user_token/service/internal/data"
	"github.com/devexps/go-microservices-demo/app/user_token/service/internal/server"
	"github.com/devexps/go-microservices-demo/app/user_token/service/internal/service"
)

// Injectors from wire.go:

// initApp init GoMicro application.
func initApp(logger log.Logger, registrar registry.Registrar, bootstrap *v1.Bootstrap) (*micro.App, func(), error) {
	client := data.NewRedisClient(bootstrap, logger)
	authenticator := data.NewAuthenticator(bootstrap)
	dataData, cleanup, err := data.NewData(logger, client, authenticator)
	if err != nil {
		return nil, nil, err
	}
	userTokenRepo := data.NewUserTokenRepo(dataData, logger)
	userTokenService := service.NewUserTokenService(logger, userTokenRepo)
	grpcServer := server.NewGRPCServer(bootstrap, logger, userTokenService)
	app := newApp(logger, registrar, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
