server:
  grpc:
    addr: "0.0.0.0:9091"
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      auth:
        method: "HS256"
        key: "some_api_key"